"""Course catalogue seed. Lessons are only ever sent to enrolled users."""

COURSES = [
    dict(id="prompt-engineering", title="AI Prompt Engineering",
         description="Talk to AI clearly and build with it: roles, constraints, structured output, labs and class projects.",
         lessons=["What prompt engineering is", "The 7 building blocks", "Roles, tasks and context", "Constraints and output formats",
                  "Examples and quality criteria", "Testing and improving prompts", "Prompt Lab", "Class projects"]),
    dict(id="animation", title="Animation Masterclass",
         description="From animation fundamentals to professional 2D/3D production, ending with a finished short film.",
         lessons=["Animation Foundations", "Story and Pre-production", "2D Animation", "3D Animation",
                  "Cinematography and Sound", "AI-Assisted Animation", "Production and Portfolio", "Capstone: animated short"]),
    dict(id="cloud-computing", title="Cloud Computing Masterclass",
         description="Cloud fundamentals to deployment and operations: compute, storage, networking, IAM, monitoring and cost control.",
         lessons=["Cloud Fundamentals", "Compute and Storage", "Networking", "Identity and Security",
                  "Data and Application Services", "DevOps and Reliability", "Cost and Governance", "Portfolio Project"]),
    dict(id="web-development", title="Web Development Masterclass",
         description="Build responsive, accessible, real-world websites with HTML, CSS, JavaScript, Git and deployment.",
         lessons=["Web Foundations", "CSS and Responsive Design", "JavaScript", "Modern Front-end",
                  "Backend Introduction", "Data and Quality", "Git and Deployment", "Portfolio Project"]),
    dict(id="app-development", title="App Development Masterclass",
         description="Plan, build, test and release mobile apps: UX, navigation, APIs, storage, testing and store release.",
         lessons=["App Development Foundations", "UI/UX and Navigation", "Programming Foundations", "Data and APIs",
                  "Accounts and Security", "Testing and Quality", "Release and Maintenance", "Portfolio Project"]),
    dict(id="full-stack", title="Full Stack Development Masterclass",
         description="Complete applications from front end to database: APIs, auth, testing, deployment and monitoring.",
         lessons=["Full Stack Foundations", "Front-end Engineering", "Backend Engineering", "Databases",
                  "Authentication and Security", "Testing and Collaboration", "Deployment and Operations", "Portfolio Project"]),
    dict(id="agentic-ai", title="Agentic AI Development Masterclass",
         description="Design reliable AI agents, tools and workflows with evaluation, guardrails and human approval checkpoints.",
         lessons=["Agentic AI Foundations", "Prompt and Model Design", "Tools and Integrations", "Memory and State",
                  "Planning and Orchestration", "Reliability and Evaluation", "Security and Deployment", "Portfolio Project"]),
    dict(id="game-development", title="Game Development Masterclass",
         description="From game design and prototyping to a playable release: loops, physics, UI, audio, testing and publishing.",
         lessons=["Game Design Foundations", "Engine and Programming", "Gameplay Systems", "World and Levels",
                  "UI, Audio, and Feedback", "Testing and Optimization", "Publishing", "Portfolio Project"]),
]

LESSONS = {c["id"]: c["lessons"] for c in COURSES}
